title: Ajani Cole | Cybersecurity Portfolio
description: Exploring cybersecurity through vulnerability testing, network analysis, and secure coding
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
