title: Ajani Cole | Cybersecurity Portfolio
description: Aspiring cybersecurity professional and computer science student at FIU, passionate about safeguarding digital systems and building secure solutions. Explore my projects, skills, and journey into the world of cybersecurity.
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
